### ISSUE TITLE
lie down powerless MQTT command

### ISSUE THREAD

**Issue by gitbnz** [MAVProxyUser/YushuTechUnitreeGo1#12]
I work with a GO1 AIR with an extrenal power supply. I use a RPI to send it MQTT commands to fullfill a walking routine. So far it works well, except that the motors are overheating with the time. I use the standDown command to have it have 15min rest every 15min routine, but in that mode the motors still draw power. I was looking for the L2+B command to lie down powerless, so I used the sniffing described, but without any result. 
I thought maybe one of you could help me out. Thanks a lot.

**Comment by aatb-ch** [comment]
You have to follow mode=5 (stand down) with a mode=7 (damped) to have the motors go soft with low torque. Simple stand down is actually worse than just letting the dog idle because it locks the legs going stiff and applying high torque (with audible noise)

**Comment by gitbnz** [comment]
Thanks. Used the following:

infot = mqttc.publish("controller/action", "damping", qos=2)
infot.wait_for_publish()
time.sleep(2)
