### ISSUE TITLE
slack group 

### ISSUE THREAD

**Issue by GabrieleCesare** [MAVProxyUser/YushuTechUnitreeGo1#15]
Hi, I am looking for the link to join slack group for unitree go1. I am a mechatronic engineering student and I am working on my master thesis in collaboration with a research center

**Comment by MAVProxyUser** [comment]
This link is valid for 7 days. https://join.slack.com/t/robotdogs/shared_invite/zt-2j9kacx36-3lTtZJow_Os7~UFrmbIi9A

**Comment by isaac-racine** [comment]
Hello, could you resend the link. I'm also a master's student working with the unitree go1 and I would like to join the slack group.

**Comment by MAVProxyUser** [comment]
This one will last for 30 days @isaac-racine 
https://join.slack.com/t/robotdogs/shared_invite/zt-2kdvfdwt0-29NnVE08iV8g0PpkYhQmhg

**Comment by chinmaynehate** [comment]
Hi @MAVProxyUser 

Could you please share an updated Slack invite link? I’m a Master’s student also working on projects with the GO1 robots, and I’d appreciate the chance to connect with others in the group. The link you shared previously is valid but it is for onboarding emails with riis.com only. Thanks!

**Comment by MAVProxyUser** [comment]
> Hi @MAVProxyUser
> 
> Could you please share an updated Slack invite link? I’m a Master’s student also working on projects with the GO1 robots, and I’d appreciate the chance to connect with others in the group. The link you shared previously is valid but it is for onboarding emails with riis.com only. Thanks!

https://join.slack.com/t/robotdogs/shared_invite/zt-2s61ukbd3-axxxt1wbirUMrq9I~IobvA
