### ISSUE TITLE
I was wondering if the linked raspberry PI on the list could use the air cheap robotic dog instead of the edu version

### ISSUE THREAD

**Issue by haxx12113** [MAVProxyUser/YushuTechUnitreeGo1#3]
I was wondering if the linked raspberry PI on the list could use the air cheap robotic dog instead of the edu version

**Comment by MAVProxyUser** [comment]
the SDK capabilities of the Air are very limited, and it physically lacks some computing power of the larger dogs. Think of the platform like an ATX mother board with parts that can be swapped out just the same. In theory you could make an air more beefy.

**Comment by haxx12113** [comment]
Can it be interpreted as replacing air with a stronger Jetson Xavier NX that can realize edu function? But is it hard to do an sdk with different versions of edu without an open source implementation? Perhaps we need to redevelop the joint based motion algorithm for four legs?

**Comment by MAVProxyUser** [comment]
Yes, Unitree staff are trying to gatekeep the product with money. You could replace the NX, but you would be missing the code that they sell with it.

**Comment by haxx12113** [comment]
In https://techshare.co.jp/faq/unitree/go1_ultrasonic.html understands: autostart file can be modified. May I ask if the core code of leg control in go1 edu can be moved? Can we try to move it to go1 pro for use.

**Comment by haxx12113** [comment]
Supplementary: Could you try to move the edu code in go1 pro as a whole so that the sdk development interface can run in go1 pro

**Comment by MAVProxyUser** [comment]
You can only do High-Level SDK development on non EDU dogs at this time. We are working on cracking the low level support. see: https://github.com/MAVProxyUser/YushuTechUnitreeGo1#sdk-usage-on-non-edu-models
