### ISSUE TITLE
[HELP WANTED] Jetson NX backup

### ISSUE THREAD

**Issue by albertoec** [MAVProxyUser/YushuTechUnitreeGo1#6]
Hello everyone,

First, I want to express my gratitude for the incredible researching work you have all done on this project. I am currently facing an issue with my Jetson NX (192.168.123.15) as it has stopped functioning. After some investigation, I have determined that the problem lies with the Linux image rather than the board itself. Unfortunately, I did not take adequate precautions and do not have a backup of the board image...

I would greatly appreciate it if any of you could provide assistance by sharing a backup of your board image. Any help would be immensely appreciated.

Thank you.

**Comment by MAVProxyUser** [comment]
Are you on our Slack group!? It may be easier to speak in real time. Can you go deeper into the problems with the Jetson? We may be able to simply give you the files off a working image. Otherwise we may want to look at removing the Jetson and using sdk-manager to rebuild it. https://developer.nvidia.com/sdk-manager

**Comment by kenloumixx** [comment]
@MAVProxyUser Hello, as who suffering from the similar issue, may I ask a question?
i am trying to reflash jetson in Unitree A1 but the laptop doesnt recognize the jetson. I powered on the robot and connnect laptop and jetson in robot with usb-c and usb-a. I want to reflash the jetson without opening the robot, so would you please show how to reflash jetson?

**Comment by MAVProxyUser** [comment]
We have backups of the Jetsons on Slack now... https://join.slack.com/t/robotdogs/shared_invite/zt-24ep8mqn4-1p42Aq7owRv9klLI~3C5Pw
